### ISSUE TITLE
Chrome extensions have changed, extension no longer fancy.

### ISSUE THREAD

**Issue by elliotcm** [alphagov/govuk-toolkit-chrome#5]
As of Chrome 48, all extension buttons have been moved out of the omnibox and into the normal extension panel.  This means that this code no longer works: https://github.com/alphagov/govuk-toolkit-chrome/blob/master/background.js#L1-L7

This means that the button provides an unexpected context window when not on gov.uk sites:
<img width="865" alt="screenshot 2016-03-27 22 29 33" src="https://cloud.githubusercontent.com/assets/109225/14067942/8ae1f344-f46b-11e5-918f-24794d93964c.png">
<img width="1034" alt="screenshot 2016-03-27 22 30 33" src="https://cloud.githubusercontent.com/assets/109225/14067943/8ee7b30c-f46b-11e5-911a-f671354a8eb0.png">

I've had a quick look for ways around this but not long enough to dig into the docs.

**Comment by tijmenb** [comment]
Hey Elliot,

Quite an unfortunate change in Chrome. For context, from [Chromium-Extensions-Announce](https://groups.google.com/a/chromium.org/forum/#!searchin/chromium-extensions/upcoming/chromium-extensions/7As9MKhav5E/dNiZDoSCCQAJ):

> The reason for this is to protect our users.  We've heard too frequently that many users are unaware of the extensions they have installed, whether this is due to sideloading, installation by phishing, or simply the user forgetting how many and which are installed.  Unfortunately, extensions consume computing resources, and may have significant security, privacy, and performance impacts.  Because of this, we've decided we need to increase user visibility.

There's no way to get the old behaviour back.

However, https://github.com/alphagov/govuk-toolkit-chrome/blob/master/background.js#L1-L7 still has effect. On non-GOV.UK pages the icon will actually be greyed out. But in our case the difference between the states is almost imperceptible:

![diff-active-non-active](https://cloud.githubusercontent.com/assets/233676/14077708/640ce1fe-f4e6-11e5-9f1f-eb17ecc59027.png)

A solution could be to make the icon white-on-black (like the favicon) so that the difference is clearer. I'll experiment with that.

**Comment by tijmenb** [comment]
Seems like the right thing to do is to use `chrome.pageAction.setIcon()` on GOV.UK pages.

https://developer.chrome.com/extensions/pageAction#method-setIcon

This way we can set the active/inactive icon ourselves. 

But somehow this method makes the original icon very fuzzy:

![screen shot 2016-03-28 at 13 49 04](https://cloud.githubusercontent.com/assets/233676/14078225/e45b21f4-f4eb-11e5-8467-e0ccdfbe513e.png)
![screen shot 2016-03-28 at 13 49 12](https://cloud.githubusercontent.com/assets/233676/14078226/e46069a2-f4eb-11e5-8e17-01c0e1782ecc.png)

I'll check with a designer tomorrow if there are pixel-fitted favicons somewhere so we can provide Chrome with correctly sized images (which should prevent this).

**Comment by elliotcm** [comment]
Is that a retina issue?  I've dug through static and can't find any larger ones.
